### ISSUE TITLE
Select needs to be clicked twice

### ISSUE THREAD

**Issue by zoopmaster** [RoleModel/optics#137]
**Describe the bug**
In Firefox, a select requires two clicks to display the options.

**To Reproduce**

0. Open Firefox
1. Go to 'https://docs.optics.rolemodel.design/?path=/docs/components-form-select--default#dropdown'
2. Click on the Dropdown.
3. The dropdown will flash.
4. Click on the Dropdown a second time.
5. The Dropdown will open.

**Expected behavior**
I would expect to click on the Dropdown only one time and it display the options.

**Screenshots**

https://user-images.githubusercontent.com/88258994/219467138-6dd7e5ed-b3ac-4536-a1b3-b62dda1ea733.mov

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 98.0.1

**Additional context**
None

**Comment by Jeremy-Walton** [comment]
This seems to be working perfectly fine in the latest version of Firefox. Latest Firefox is v110.0

Does this happen with other Select Elements in your version of Firefox, or specifically with the Optics Select?

**Comment by zoopmaster** [comment]
I haven't noticed it with any other selects. And, this has never happened on any other RMS projects to date.

**Comment by Jeremy-Walton** [comment]
Try updating your firefox

**Comment by zoopmaster** [comment]
That did it.
