### ISSUE TITLE
Better utility class docs

### ISSUE THREAD

**Issue by jdmcleod** [RoleModel/optics#14]
~~Seems like we could add more helpful utilities. See Maverick for reference~~

- Display none, visibility hidden
- Min width, max width
- Hoverable
- Overflow hidden / scroll
- Position relative?

This has been addressed by https://github.com/RoleModel/rolemodel-design-system/pull/105

Now this is about adding documentation for our existing utilities

**Comment by Jeremy-Walton** [comment]
This has finally been addressed in https://github.com/RoleModel/optics/pull/148
