### ISSUE TITLE
Investigate mobile layout issues with panel

### ISSUE THREAD

**Issue by scriswell** [RoleModel/optics#41]
Note: switching to Shoelace will likely correct this issue.

**Comment by Jeremy-Walton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Side Panel](https://trello.com/c/RKaEKg10/19-side-panel)

**Comment by Jeremy-Walton** [comment]
This problem only occurs with the current panel add-on. This add-on is being removed in favor of a full component which will be developed in the attached task. As such, I am going to close this issue.
